title: Zach Meyen # your name (or website title) here
logo: "/images/Headshot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I graduated from the University of Kansas in 2019 with a Bachelor of Science degree in Business Data Analytics.
  <br><br>
  In the pursuit of constantly bettering myself, I am currently pursuing a master's degree from The Georgia Institute of Technology's Online Master of Analytics program. I am choosing to work full time while taking courses part time over the next two years.
  I like to focus my analytical efforts on predictave algorithms, simulation, and the application of insights derived from models in real life decisions.
  <br><br>
  Strong background in R, SQL, and Python.
  <a href="https://www.linkedin.com/in/zachmeyen/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
