title: Zach Meyen # your name (or website title) here
logo: "/images/Headshot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Education
 <br><br>
 Bachelors in Business Analytics | Univerisity of Kansas | 2015 - 2019
 Masters in Analytics | Georgia Tech | 2020 - Present
  <br><br>
  I like to focus my analytical efforts on predictive algorithms, simulation, and the application of insights derived from models in real life decisions.
  <br><br>
  Strong background in R, SQL, and Python.
  <br><br>
  Currently work in unmanned aviation and aerial survey. 
  <br><br>
  <a href="https://www.linkedin.com/in/zachmeyen/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
